name: Badge Request
description: Request a badge that you would like to see be added to the badge list.
title: "[Badge Request]: "
labels: ["🙏 badge request"]
projects: ["inttter/md-badges"]
assignees:
  - inttter
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this request, make sure the badge does not **already exist** within the current badge list. Preferably, it should also have a **valid** icon on [SimpleIcons](https://simpleicons.org) to simplify the process of adding it to the list.
  - type: input
    id: name
    attributes:
      label: Badge Name
      description: What is the name of the badge?
      placeholder: eg. React
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description about who/what the badge is for. For example, you can link a URL to a website.
      placeholder: This badge is for [NAME]...
    validations:
      required: true