name: Issue Report
description: Report something that is incorrect or not working.
title: "[Bug]: "
labels: ["🐛 bug"]
projects: ["inttter/md-badges"]
body:
  - type: markdown
    attributes:
      value: |
        Search for your issue in the [issue listing](https://github.com/inttter/md-badges/issues) to make sure your issue is not a duplicate.
  - type: textarea
    attributes:
      label: Description of issue
      description: Describe the issue you have and give any additional details.
      placeholder: The issue is...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots/Videos
      description: If applicable, drag a screenshot or video into this box that shows this issue.
    validations:
      required: false